CREATE TABLE tasks
(
	id			NUMBER(3),
	task_name		VARCHAR(100),
	deadline		VARCHAR2(100),
	priority		VARCHAR2(100),
	CONSTRAINT STUDENT_CONS PRIMARY KEY(id)
);

CREATE SEQUENCE task_seq START WITH 100 INCREMENT BY 1;